(function(M,common,patcher,plugin,logger,ui,utils){
"use strict";
/* Kettu ImageTools v1.0.0 */
const React=common?.React,RN=common?.ReactNative||{},storage=plugin?.storage||{};const unpatches=[];let LazyActionSheet=null,ActionSheetRow=null,Clipboard=null,MediaSaver=null,Downloader=null;const diag={sheet:false,saver:false,downloader:false,saved:0,opened:0,copied:0,lastError:""};
function err(w,e){diag.lastError=`${w}: ${e?.message||e}`;try{logger?.error?.(diag.lastError,e)}catch{}}
function toast(s){try{ui?.showToast?.(String(s))}catch{}}
function defaults(){for(const[k,v]of Object.entries({enabled:true,avatar:true,attachments:true,emojis:true,stickers:true,copyUrl:true,openFallback:true,avatarSize:4096,maxMenuItems:8,preferGif:true}))if(storage[k]===undefined)storage[k]=v}
function avatarUrl(u){if(!u?.id||!u?.avatar)return null;const ext=String(u.avatar).startsWith("a_")?"gif":"png";const size=Math.max(128,Math.min(4096,Number(storage.avatarSize)||4096));return `https://cdn.discordapp.com/avatars/${u.id}/${u.avatar}.${ext}?size=${size}`}
function emojiUrls(content){const out=[];const re=/<(a?):([\w~]+):(\d+)>/g;let m;while((m=re.exec(String(content||"")))&&out.length<20)out.push({kind:"emoji",name:m[2],url:`https://cdn.discordapp.com/emojis/${m[3]}.${m[1]?"gif":"png"}?size=4096&quality=lossless`});return out}
function stickerUrl(s){if(!s?.id)return null;const fmt=s.format_type??s.formatType;const ext=fmt===2?"png":fmt===4?"gif":fmt===3?"json":"png";return `https://media.discordapp.net/stickers/${s.id}.${ext}?size=4096&quality=lossless`}
function collectMessage(m){const a=[];if(storage.avatar){const u=avatarUrl(m?.author);if(u)a.push({kind:"avatar",name:`${m.author?.username||"user"}_avatar`,url:u})}if(storage.attachments)for(const x of m?.attachments||[])if(x?.url)a.push({kind:"attachment",name:x.filename||`attachment_${x.id||Date.now()}`,url:x.url});if(storage.stickers)for(const s of m?.sticker_items||m?.stickers||[]){const u=stickerUrl(s);if(u)a.push({kind:"sticker",name:s.name||`sticker_${s.id}`,url:u})}if(storage.emojis)a.push(...emojiUrls(m?.content));const seen=new Set();return a.filter(x=>x.url&&!seen.has(x.url)&&(seen.add(x.url),true)).slice(0,Math.max(1,Math.min(20,Number(storage.maxMenuItems)||8)))}
function discover(){try{Clipboard=M.findByProps?.("setString")}catch{}for(const ps of [["saveImageToCameraRoll"],["saveToCameraRoll"],["saveImage"],["saveMedia"]]){try{const x=M.findByProps?.(...ps);if(x){MediaSaver=x;break}}catch{}}for(const ps of [["downloadFile"],["download"],["enqueueDownload"]]){try{const x=M.findByProps?.(...ps);if(x){Downloader=x;break}}catch{}}diag.saver=!!MediaSaver;diag.downloader=!!Downloader}
async function copy(url){try{Clipboard?.setString?.(url);diag.copied++;toast("Medya linki kopyalandı")}catch(e){err("copy",e)}}
async function open(url){try{if(typeof RN.Linking?.openURL==="function"){await RN.Linking.openURL(url);diag.opened++;return true}}catch(e){err("open",e)}return false}
async function save(item){const url=item?.url;if(!url)return;try{if(MediaSaver){for(const n of ["saveImageToCameraRoll","saveToCameraRoll","saveImage","saveMedia"]){if(typeof MediaSaver[n]!=="function")continue;try{await MediaSaver[n](url,item.name);diag.saved++;toast("Galeriye kaydedildi");return}catch{try{await MediaSaver[n]({url,filename:item.name});diag.saved++;toast("Galeriye kaydedildi");return}catch{}}}}if(Downloader){for(const n of ["downloadFile","download","enqueueDownload"]){if(typeof Downloader[n]!=="function")continue;try{await Downloader[n]({url,fileName:item.name,filename:item.name});diag.saved++;toast("İndirme başlatıldı");return}catch{try{await Downloader[n](url,item.name);diag.saved++;toast("İndirme başlatıldı");return}catch{}}}}if(storage.openFallback&&await open(url)){toast("Doğrudan kaydetme API'si yok, medya açıldı");return}await copy(url)}catch(e){err("save",e);toast(`Kaydedilemedi: ${e.message}`)}}
function findRows(root){const seen=new WeakSet();let b=1200;function w(v,d){if(v==null||d>11||b--<0)return null;if(Array.isArray(v)&&v.some(x=>x?.props&&typeof x.props.onPress==="function"))return v;if(typeof v!=="object")return null;if(seen.has(v))return null;seen.add(v);for(const k of Object.keys(v)){if(typeof v[k]==="function")continue;const r=w(v[k],d+1);if(r)return r}return null}return w(root,0)}
function addRows(rows,items,prefix){if(!rows||!items?.length)return;if(rows.some(x=>x?.props?.__kit))return;items.forEach((it,i)=>{const label=it.kind==="avatar"?"🖼 Profil fotoğrafını kaydet":it.kind==="sticker"?`🏷 Çıkartmayı kaydet: ${it.name}`:it.kind==="emoji"?`😀 Emojiyi kaydet: ${it.name}`:`📎 Kaydet: ${it.name}`;rows.push(React.createElement(ActionSheetRow,{key:`${prefix}-${i}`,__kit:true,label,onPress:()=>{LazyActionSheet.hideActionSheet?.();save(it)}}));if(storage.copyUrl)rows.push(React.createElement(ActionSheetRow,{key:`${prefix}-copy-${i}`,__kit:true,label:`🔗 Linki kopyala: ${it.name}`,onPress:()=>{LazyActionSheet.hideActionSheet?.();copy(it.url)}}))})}
function installSheets(){try{LazyActionSheet=M.findByProps?.("openLazy","hideActionSheet");ActionSheetRow=M.findByProps?.("ActionSheetRow")?.ActionSheetRow||common?.ActionSheetRow||ui?.components?.FormRow;if(!LazyActionSheet||!ActionSheetRow)return;unpatches.push(patcher.before("openLazy",LazyActionSheet,([component,key,props])=>{if(!storage.enabled||!component?.then)return;let items=[];if(props?.message)items=collectMessage(props.message);else if(storage.avatar&&(props?.user||props?.profile?.user)){const u=props.user||props.profile.user,v=avatarUrl(u);if(v)items=[{kind:"avatar",name:`${u.username||"user"}_avatar`,url:v}]}if(!items.length)return;component.then(mod=>{if(typeof mod?.default!=="function")return;const u=patcher.after("default",mod,(_,tree)=>{setTimeout(()=>{try{u()}catch{}},0);addRows(findRows(tree),items,"kit")});}).catch?.(()=>{})}));diag.sheet=true}catch(e){err("sheet",e)}}
function Settings(){if(!React||!RN.View||!RN.Text)return null;const[,f]=React.useReducer(x=>x+1,0),S=(k,v)=>{storage[k]=v;f()};const V=RN.View,T=RN.Text,SV=RN.ScrollView||V,Sw=RN.Switch,I=RN.TextInput;const st={root:{padding:16,gap:10},h:{fontSize:22,fontWeight:"700",color:"#fff"},c:{padding:12,borderRadius:10,backgroundColor:"#2b2d31",gap:8},t:{fontSize:15,color:"#fff",flex:1},s:{fontSize:12,color:"#b5bac1"},r:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},i:{backgroundColor:"#1e1f22",color:"#fff",padding:9,borderRadius:7}};const row=(l,k)=>React.createElement(V,{style:st.r},React.createElement(T,{style:st.t},l),Sw&&React.createElement(Sw,{value:!!storage[k],onValueChange:v=>S(k,v)}));return React.createElement(SV,{contentContainerStyle:st.root},React.createElement(T,{style:st.h},"ImageTools"),React.createElement(V,{style:st.c},row("Aktif","enabled"),row("Profil fotoğrafları","avatar"),row("Mesaj ekleri","attachments"),row("Custom emojiler","emojis"),row("Çıkartmalar","stickers"),row("Link kopyala seçenekleri","copyUrl"),row("Kaydet API yoksa medyayı aç","openFallback")),React.createElement(V,{style:st.c},React.createElement(T,{style:st.s},"Avatar çözünürlüğü"),I&&React.createElement(I,{style:st.i,value:String(storage.avatarSize),keyboardType:"numeric",onChangeText:v=>S("avatarSize",v)}),React.createElement(T,{style:st.s},"Menüde maksimum medya"),I&&React.createElement(I,{style:st.i,value:String(storage.maxMenuItems),keyboardType:"numeric",onChangeText:v=>S("maxMenuItems",v)})),React.createElement(V,{style:st.c},React.createElement(T,{style:st.s},`Mesaj/profil menüsü ${diag.sheet?"OK":"YOK"} | Galeri saver ${diag.saver?"OK":"YOK"} | Downloader ${diag.downloader?"OK":"YOK"}\nKaydedilen ${diag.saved} | Açılan ${diag.opened} | Link kopya ${diag.copied}${diag.lastError?`\n${diag.lastError}`:""}`),React.createElement(T,{style:st.s},"Normal emoji/sticker kullanımını patchlemez. Yalnızca uzun basma menüsüne medya işlemleri ekler, yani FakeNitro ile gereksiz bilek güreşi yapmaz.")))}
function onLoad(){defaults();discover();installSheets()}function onUnload(){while(unpatches.length){try{unpatches.pop()?.()}catch{}}}
return {onLoad,onUnload,settings:Settings,__test:{avatarUrl,emojiUrls,stickerUrl,collectMessage}};
})(vendetta.metro,vendetta.metro.common,vendetta.patcher,vendetta.plugin,vendetta.logger,vendetta.ui,vendetta.utils)
