const fs=require("fs"),vm=require("vm"),assert=require("assert"),{TextEncoder,TextDecoder}=require("util"),{webcrypto}=require("crypto");
function makeEnv(extra={}){
 const storage=extra.storage||{}; const modules=[]; const stores={}; const names={};
 function add(m){modules.push(m);return m} function store(n,v){stores[n]=v;return v} function named(n,v){names[n]=v;return v}
 const patcher={
  before(name,obj,cb){const orig=obj[name];obj[name]=function(...args){cb(args);return orig.apply(this,args)};return()=>{obj[name]=orig}},
  after(name,obj,cb){const orig=obj[name];obj[name]=function(...args){const r=orig.apply(this,args);const n=cb(args,r);return n===undefined?r:n};return()=>{obj[name]=orig}},
  instead(name,obj,cb){const orig=obj[name];obj[name]=function(...args){const self=this;const call=(...a)=>orig.apply(self,a.length?a:args);return cb.call(self,args,call)};return()=>{obj[name]=orig}}
 };
 const React={createElement:(type,props,...children)=>({type,props:{...(props||{}),children:children.length<=1?children[0]:children}}),Fragment:"Fragment"};
 const RN={View:function View(){},Text:function Text(){},ScrollView:function ScrollView(){},Switch:function Switch(){},Pressable:function Pressable(){},TouchableOpacity:function TouchableOpacity(){},TextInput:function TextInput(){},Image:function Image(){},Vibration:{calls:[],vibrate(x){this.calls.push(x)}},Linking:{opened:[],async openURL(u){this.opened.push(u);return true}},processColor:x=>x,StyleSheet:{flatten:a=>a}};
 const common={React,ReactNative:RN};
 const metro={common,findByProps:(...ps)=>modules.find(m=>m&&ps.every(p=>p in m)),findByStoreName:n=>stores[n],findByName:n=>names[n]};
 const vendetta={metro,patcher,plugin:{storage},logger:{log(){},error(){}},ui:{toasts:[],showToast(s){this.toasts.push(String(s))},components:{}},utils:{}};
 const ctx={vendetta,console,TextEncoder,TextDecoder,crypto:webcrypto,btoa:s=>Buffer.from(s,"binary").toString("base64"),atob:s=>Buffer.from(s,"base64").toString("binary"),fetch:extra.fetch||global.fetch,setTimeout:(fn)=>{fn();return 1},clearTimeout(){},setInterval:()=>1,clearInterval(){},Date,Map,Set,WeakMap,WeakSet,Array,Object,String,Number,Math,JSON,RegExp,Promise,Uint8Array,Error};ctx.globalThis=ctx;
 return {ctx,storage,modules,stores,names,add,store,named,patcher,RN,vendetta};
}
function load(env){const code=fs.readFileSync(require("path").join(__dirname,"index.js"),"utf8");return vm.runInNewContext(code,env.ctx,{filename:"index.js"});}

(()=>{const env=makeEnv();const messages=new Map();env.store("MessageStore",{getMessage:(ch,id)=>messages.get(`${ch}:${id}`),emitChange(){}});env.store("ChannelStore",{emitChange(){}});class RowManager{generate(row){return {id:row.message.id,body:{content:row.message.content,style:{}},message:{id:row.message.id,content:row.message.content}}}invalidateMessage(){}}env.named("RowManager",RowManager);const flux=env.add({subscribe(){},dispatch(a){if(a.type==="MESSAGE_CREATE")messages.set(`${a.message.channel_id}:${a.message.id}`,a.message);else if(a.type==="MESSAGE_UPDATE")messages.set(`${a.channelId||a.message.channel_id}:${a.message.id}`,a.message);else if(a.type==="MESSAGE_DELETE")messages.delete(`${a.channelId}:${a.id}`);return a}});env.add({sendMessage(){},editMessage(){},startEditMessage(){}});const p=load(env);p.onLoad();const m={id:"1",channel_id:"c",content:"hello",author:{id:"u",username:"Bob"},attachments:[]};flux.dispatch({type:"MESSAGE_CREATE",message:m});flux.dispatch({type:"MESSAGE_DELETE",channelId:"c",id:"1"});const kept=messages.get("c:1");assert(kept&&kept.__kettuMessageLoggerDeleted);let row=new RowManager().generate({message:kept});const txt=JSON.stringify(row);assert(txt.includes("#f04747")||txt.includes("f04747"),"deleted row should be red");env.storage.deletedStyle="overlay";row=new RowManager().generate({message:kept});assert(JSON.stringify(row).includes("rgba(240,71,71,0.18)"));const m2={id:"2",channel_id:"c",content:"a",author:{id:"u",username:"Bob"},attachments:[]};flux.dispatch({type:"MESSAGE_CREATE",message:m2});const up={...m2,content:"b",edited_timestamp:"2026-09-08T20:00:00.000Z"};flux.dispatch({type:"MESSAGE_UPDATE",channelId:"c",message:up});flux.dispatch({type:"MESSAGE_UPDATE",channelId:"c",message:up});const edited=messages.get("c:2");assert((edited.content.match(/✎/g)||[]).length===1,"duplicate edit history");p.onUnload();console.log("PASS MessageLogger v2.3");})();
