(function(M,common,patcher,plugin,logger,ui,utils){
"use strict";
/* Kettu GhostPingLogger v1.0.0 */
const React=common?.React,RN=common?.ReactNative||{},storage=plugin?.storage||{};const unpatches=[];const watched=new Map(),handled=new Set();let Flux=null,MessageStore=null,UserStore=null,GuildMemberStore=null;const diag={flux:false,creates:0,deletes:0,ghosts:0,compatDeletes:0,lastError:""};
function err(w,e){diag.lastError=`${w}: ${e?.message||e}`;try{logger?.error?.(diag.lastError,e)}catch{}}
function defaults(){for(const[k,v]of Object.entries({enabled:true,direct:true,everyone:true,here:true,roles:true,ignoreBots:false,notify:true,vibrate:true,persist:true,maxLogs:200}))if(storage[k]===undefined)storage[k]=v;if(!Array.isArray(storage.logs))storage.logs=[]}
function k(ch,id){return `${ch||"?"}:${id||"?"}`}
function current(){return UserStore?.getCurrentUser?.()}
function mentionInfo(m){const me=current();if(!me?.id||!m)return null;const content=String(m.content||"");const direct=(m.mentions||[]).some(x=>String(x?.id||x)===String(me.id))||content.includes(`<@${me.id}>`)||content.includes(`<@!${me.id}>`);const everyone=!!m.mention_everyone||/@everyone\b/i.test(content);const here=/@here\b/i.test(content);let role=false;try{const guildId=m.guild_id||m.guildId;const member=GuildMemberStore?.getMember?.(guildId,me.id);const roles=new Set(member?.roles||[]);role=(m.mention_roles||m.mentionRoles||[]).some(x=>roles.has(String(x)))||[...roles].some(id=>content.includes(`<@&${id}>`))}catch{};const kinds=[];if(direct&&storage.direct)kinds.push("direct");if(everyone&&storage.everyone)kinds.push("everyone");if(here&&storage.here)kinds.push("here");if(role&&storage.roles)kinds.push("role");return kinds.length?kinds:null}
function cache(m){if(!storage.enabled||!m?.id)return;const kinds=mentionInfo(m);if(!kinds)return;if(storage.ignoreBots&&m.author?.bot)return;const ch=m.channel_id||m.channelId;watched.set(k(ch,m.id),{channelId:ch,id:m.id,content:String(m.content||""),authorId:m.author?.id,authorName:m.author?.globalName||m.author?.global_name||m.author?.username||"unknown",kinds,createdAt:Date.now()});diag.creates++}
function logGhost(info){const id=k(info.channelId,info.id);if(handled.has(id))return;handled.add(id);setTimeout(()=>handled.delete(id),30000);const e={...info,deletedAt:Date.now()};storage.logs.unshift(e);const max=Math.max(20,Math.min(2000,Number(storage.maxLogs)||200));if(storage.logs.length>max)storage.logs.length=max;diag.ghosts++;if(storage.vibrate)try{RN.Vibration?.vibrate?.([0,80,80,160])}catch{};if(storage.notify)try{ui?.showToast?.(`👻 Ghost ping: ${info.authorName} • ${info.content.slice(0,100)}`)}catch{}}
function handleDelete(ch,id,fallback){const q=k(ch,id);let info=watched.get(q);if(!info&&fallback){const kinds=mentionInfo(fallback);if(kinds)info={channelId:ch,id,content:String(fallback.content||""),authorId:fallback.author?.id,authorName:fallback.author?.globalName||fallback.author?.username||"unknown",kinds,createdAt:Date.now()}}if(info){logGhost(info);watched.delete(q)}diag.deletes++}
function install(){try{Flux=M.findByProps?.("dispatch","subscribe");MessageStore=M.findByStoreName?.("MessageStore");UserStore=M.findByStoreName?.("UserStore");GuildMemberStore=M.findByStoreName?.("GuildMemberStore");if(!Flux)return;diag.flux=true;unpatches.push(patcher.before("dispatch",Flux,([a])=>{try{if(!a?.type)return;if(a.type==="MESSAGE_CREATE")return cache(a.message);if(a.type==="MESSAGE_DELETE"){const ch=a.channelId||a.channel_id,id=a.id||a.messageId||a.message_id;const m=MessageStore?.getMessage?.(ch,id);return handleDelete(ch,id,m)}if(a.type==="MESSAGE_DELETE_BULK"){const ch=a.channelId||a.channel_id;for(const id of a.ids||a.messageIds||[])handleDelete(ch,id,MessageStore?.getMessage?.(ch,id));return}if(a.type==="MESSAGE_UPDATE"&&a.message?.__kettuMessageLoggerDeleted){diag.compatDeletes++;const m=a.message,ch=m.channel_id||m.channelId||a.channelId;handleDelete(ch,m.id,m)}}catch(e){err("dispatch",e)}}))}catch(e){err("install",e)}}
function Settings(){if(!React||!RN.View||!RN.Text)return null;const[,f]=React.useReducer(x=>x+1,0),S=(k,v)=>{storage[k]=v;f()};const V=RN.View,T=RN.Text,SV=RN.ScrollView||V,Sw=RN.Switch,I=RN.TextInput,P=RN.Pressable||RN.TouchableOpacity||V;const st={root:{padding:16,gap:10},h:{fontSize:22,fontWeight:"700",color:"#fff"},c:{padding:12,borderRadius:10,backgroundColor:"#2b2d31",gap:8},t:{fontSize:15,color:"#fff",flex:1},s:{fontSize:12,color:"#b5bac1"},r:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},i:{backgroundColor:"#1e1f22",color:"#fff",padding:9,borderRadius:7},b:{padding:10,borderRadius:7,backgroundColor:"#404249"},bt:{color:"#fff",textAlign:"center",fontWeight:"600"},log:{fontSize:13,color:"#dbdee1",paddingVertical:3}};const row=(l,k)=>React.createElement(V,{style:st.r},React.createElement(T,{style:st.t},l),Sw&&React.createElement(Sw,{value:!!storage[k],onValueChange:v=>S(k,v)}));const btn=(l,fn)=>React.createElement(P,{onPress:fn,style:st.b},React.createElement(T,{style:st.bt},l));return React.createElement(SV,{contentContainerStyle:st.root},React.createElement(T,{style:st.h},"GhostPingLogger"),React.createElement(V,{style:st.c},row("Aktif","enabled"),row("Direkt @mention","direct"),row("@everyone","everyone"),row("@here","here"),row("Rol mention","roles"),row("Botları atla","ignoreBots"),row("Toast bildirimi","notify"),row("Titreşim","vibrate")),React.createElement(V,{style:st.c},React.createElement(T,{style:st.s},"Maks log"),I&&React.createElement(I,{style:st.i,value:String(storage.maxLogs),keyboardType:"numeric",onChangeText:v=>S("maxLogs",v)}),btn("Tüm ghost ping kayıtlarını temizle",()=>{storage.logs=[];f()})),React.createElement(V,{style:st.c},React.createElement(T,{style:st.t},"Son ghost pingler"),...(storage.logs.slice(0,60).length?storage.logs.slice(0,60).map((x,i)=>React.createElement(T,{key:String(i),style:st.log},`👻 ${new Date(x.deletedAt).toLocaleTimeString()} ${x.authorName} [${(x.kinds||[]).join(", ")}]\n${x.content||"(metin yok)"}`)):[React.createElement(T,{key:"empty",style:st.s},"Henüz ghost ping yok.")])),React.createElement(V,{style:st.c},React.createElement(T,{style:st.s},`Flux ${diag.flux?"OK":"YOK"} | Ghost ${diag.ghosts} | Delete ${diag.deletes} | MessageLogger uyumluluk ${diag.compatDeletes}${diag.lastError?`\n${diag.lastError}`:""}`)))}
function onLoad(){defaults();install()}function onUnload(){while(unpatches.length){try{unpatches.pop()?.()}catch{}}watched.clear();handled.clear()}
return {onLoad,onUnload,settings:Settings,__test:{mentionInfo,cache,handleDelete}};
})(vendetta.metro,vendetta.metro.common,vendetta.patcher,vendetta.plugin,vendetta.logger,vendetta.ui,vendetta.utils)
