(function(M,common,patcher,plugin,logger,ui,utils){
"use strict";
/* Kettu BetterTyping v1.0.0 */
const React=common?.React,RN=common?.ReactNative||{},storage=plugin?.storage||{};const unpatches=[];const typing=new Map();let Flux=null,UserStore=null,SelectedChannelStore=null,TypingStore=null,timer=null;const diag={flux:false,textHook:false,typingAction:false,blocked:0,events:0,renders:0,lastError:""};
function err(w,e){diag.lastError=`${w}: ${e?.message||e}`;try{logger?.error?.(diag.lastError,e)}catch{}}
function defaults(){for(const[k,v]of Object.entries({enabled:true,showSeconds:true,separateLines:true,showMultiple:true,hideOwnTyping:false,hideSelfLocally:true,maxUsers:5,expireSeconds:12,compact:false}))if(storage[k]===undefined)storage[k]=v}
function chKey(ch){return String(ch||"?")}
function add(ch,u,ts){if(!ch||!u)return;let m=typing.get(chKey(ch));if(!m){m=new Map();typing.set(chKey(ch),m)}if(!m.has(String(u)))m.set(String(u),Number(ts)||Date.now());else if(Date.now()-m.get(String(u))>15000)m.set(String(u),Date.now())}
function del(ch,u){typing.get(chKey(ch))?.delete?.(String(u))}
function clean(){const ttl=Math.max(5,Math.min(30,Number(storage.expireSeconds)||12))*1000,now=Date.now();for(const [ch,m] of typing){for(const [u,t]of m)if(now-t>ttl)m.delete(u);if(!m.size)typing.delete(ch)}try{TypingStore?.emitChange?.()}catch{}}
function currentChannel(){try{return SelectedChannelStore?.getChannelId?.()||SelectedChannelStore?.getLastSelectedChannelId?.()}catch{return null}}
function userName(id){try{const u=UserStore?.getUser?.(id);return u?.globalName||u?.global_name||u?.username||String(id)}catch{return String(id)}}
function list(ch){clean();const self=String(UserStore?.getCurrentUser?.()?.id||"");const m=typing.get(chKey(ch))||new Map();let a=[...m].filter(([id])=>!(storage.hideSelfLocally&&id===self)).sort((x,y)=>x[1]-y[1]);return a.slice(0,Math.max(1,Math.min(20,Number(storage.maxUsers)||5)))}
function format(ch){const a=list(ch);if(!a.length)return null;const now=Date.now();const lines=a.map(([id,t])=>{const sec=Math.max(0,Math.floor((now-t)/1000));return storage.showSeconds?`${userName(id)} ${sec} saniyedir yazıyor...`:`${userName(id)} yazıyor...`});if(!storage.showMultiple&&lines.length>1)return `${lines.length} kişi yazıyor...`;return storage.separateLines?lines.join("\n"):lines.join(", ")}
function installFlux(){try{Flux=M.findByProps?.("dispatch","subscribe");UserStore=M.findByStoreName?.("UserStore");SelectedChannelStore=M.findByStoreName?.("SelectedChannelStore")||M.findByProps?.("getChannelId","getVoiceChannelId");TypingStore=M.findByStoreName?.("TypingStore")||M.findByProps?.("getTypingUsers");if(!Flux)return;diag.flux=true;unpatches.push(patcher.after("dispatch",Flux,([a])=>{try{if(!a?.type)return;const type=String(a.type);const ch=a.channelId||a.channel_id;const u=a.userId||a.user_id||a.user?.id;if(type==="TYPING_START"||type==="TYPING_START_LOCAL"){add(ch,u,a.timestamp||Date.now());diag.events++}else if(type==="TYPING_STOP"||type==="TYPING_STOP_LOCAL"||type==="MESSAGE_CREATE"){if(type==="MESSAGE_CREATE")del(a.message?.channel_id||a.message?.channelId,a.message?.author?.id);else del(ch,u)}}catch(e){err("flux",e)}}));}catch(e){err("installFlux",e)}}
function installTextHook(){const candidates=[];try{const a=M.findByProps?.("useTypingText");if(a)candidates.push([a,"useTypingText"])}catch{}try{const b=M.findByProps?.("getTypingText");if(b)candidates.push([b,"getTypingText"])}catch{}for(const [mod,name] of candidates){if(typeof mod?.[name]!=="function")continue;try{unpatches.push(patcher.after(name,mod,(args,res)=>{if(!storage.enabled)return;let ch=args?.[0]?.channelId||args?.[0]?.id||args?.[0];if(typeof ch!=="string"&&typeof ch!=="number")ch=currentChannel();const t=format(ch);if(!t)return res;diag.renders++;if(typeof res==="string")return t;if(res&&typeof res==="object"){if("text" in res)return {...res,text:t};if("typingText" in res)return {...res,typingText:t}}return t}));diag.textHook=true}catch(e){err(name,e)}}}
function installHideOwn(){const propSets=[["startTyping","stopTyping"],["startTyping"],["sendTyping"]];const seen=new Set();for(const ps of propSets){try{const mod=M.findByProps?.(...ps);if(!mod||seen.has(mod))continue;seen.add(mod);for(const n of ["startTyping","sendTyping"]){if(typeof mod[n]!=="function")continue;unpatches.push(patcher.instead(n,mod,function(args,orig){if(storage.enabled&&storage.hideOwnTyping){diag.blocked++;return undefined}return orig.apply(this,args)}));diag.typingAction=true}}catch(e){err("hideOwn",e)}}}
function installJsxFallback(){try{const jsx=M.findByProps?.("jsx","jsxs");if(!jsx)return;for(const n of ["jsx","jsxs"]){if(typeof jsx[n]!=="function")continue;unpatches.push(patcher.before(n,jsx,args=>{try{if(!storage.enabled)return;const type=args?.[0],props=args?.[1];const name=type?.displayName||type?.name||"";if(!/TypingIndicator/i.test(name)||!props)return;const t=format(props.channelId||props.channel?.id||currentChannel());if(!t)return;const p={...props};for(const k of ["text","typingText","children","label"])if(typeof p[k]==="string"){p[k]=t;args[1]=p;diag.renders++;return}}catch(e){err("jsx",e)}}))}}catch(e){err("jsxInstall",e)}}
function Settings(){if(!React||!RN.View||!RN.Text)return null;const[,f]=React.useReducer(x=>x+1,0),S=(k,v)=>{storage[k]=v;f()};const V=RN.View,T=RN.Text,SV=RN.ScrollView||V,Sw=RN.Switch,I=RN.TextInput;const st={root:{padding:16,gap:10},h:{fontSize:22,fontWeight:"700",color:"#fff"},c:{padding:12,borderRadius:10,backgroundColor:"#2b2d31",gap:8},t:{fontSize:15,color:"#fff",flex:1},s:{fontSize:12,color:"#b5bac1"},r:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},i:{backgroundColor:"#1e1f22",color:"#fff",padding:10,borderRadius:7}};const row=(l,k)=>React.createElement(V,{style:st.r},React.createElement(T,{style:st.t},l),Sw&&React.createElement(Sw,{value:!!storage[k],onValueChange:v=>S(k,v)}));return React.createElement(SV,{contentContainerStyle:st.root},React.createElement(T,{style:st.h},"BetterTyping"),React.createElement(V,{style:st.c},row("Aktif","enabled"),row("Kaç saniyedir yazdığını göster","showSeconds"),row("Kişileri ayrı satırlarda göster","separateLines"),row("Birden fazla kişiyi isimleriyle göster","showMultiple"),row("Kendi typing event'imi gönderme","hideOwnTyping"),row("Kendimi yerel listede gösterme","hideSelfLocally")),React.createElement(V,{style:st.c},React.createElement(T,{style:st.s},"Maksimum gösterilecek kişi"),I&&React.createElement(I,{style:st.i,value:String(storage.maxUsers),keyboardType:"numeric",onChangeText:v=>S("maxUsers",v)}),React.createElement(T,{style:st.s},"Typing event zaman aşımı (saniye)"),I&&React.createElement(I,{style:st.i,value:String(storage.expireSeconds),keyboardType:"numeric",onChangeText:v=>S("expireSeconds",v)})),React.createElement(V,{style:st.c},React.createElement(T,{style:st.s},`Flux ${diag.flux?"OK":"YOK"} | Metin hook ${diag.textHook?"OK":"YOK"} | Typing bloklama ${diag.typingAction?"OK":"YOK"}\nEvent ${diag.events} | Render ${diag.renders} | Gönderimi engellenen ${diag.blocked}${diag.lastError?`\n${diag.lastError}`:""}`),React.createElement(T,{style:st.s},format(currentChannel())||"Şu an yazan yok.")))}
function onLoad(){defaults();installFlux();installTextHook();installHideOwn();installJsxFallback();timer=setInterval(clean,1000)}function onUnload(){if(timer)clearInterval(timer);while(unpatches.length){try{unpatches.pop()?.()}catch{}}typing.clear()}
return {onLoad,onUnload,settings:Settings,__test:{add,del,list,format,clean}};
})(vendetta.metro,vendetta.metro.common,vendetta.patcher,vendetta.plugin,vendetta.logger,vendetta.ui,vendetta.utils)
