(function(M,common,patcher,plugin,logger,ui,utils){
"use strict";
/* Kettu ChannelTabs v1.0.0 */
const React=common?.React,RN=common?.ReactNative||{},storage=plugin?.storage||{};const unpatches=[];let ChannelStore=null,SelectedChannelStore=null,ChannelRouter=null,Nav=null,LazyActionSheet=null,ActionSheetRow=null;const diag={jsx:false,sheet:false,navigation:false,renders:0,pins:0,lastError:""};let guard=false;
function err(w,e){diag.lastError=`${w}: ${e?.message||e}`;try{logger?.error?.(diag.lastError,e)}catch{}}
function defaults(){if(!Array.isArray(storage.tabs))storage.tabs=[];for(const[k,v]of Object.entries({enabled:true,maxTabs:8,showNames:true,showClose:true,compact:false,haptic:true,position:"aboveComposer"}))if(storage[k]===undefined)storage[k]=v}
function currentId(){try{return String(SelectedChannelStore?.getChannelId?.()||SelectedChannelStore?.getLastSelectedChannelId?.()||"")}catch{return ""}}
function channel(id){try{return ChannelStore?.getChannel?.(id)||null}catch{return null}}
function nameOf(c){if(!c)return "?";return c.name||(c.recipients?.length?"DM":"Kanal")}
function pin(c){if(!c?.id)return;const id=String(c.id),existing=storage.tabs.find(t=>t.id===id);if(existing)return;const max=Math.max(1,Math.min(20,Number(storage.maxTabs)||8));while(storage.tabs.length>=max)storage.tabs.shift();storage.tabs.push({id,guildId:c.guild_id||c.guildId||null,name:nameOf(c),type:c.type??null});diag.pins++;try{ui?.showToast?.(`${nameOf(c)} sekmeye sabitlendi`)}catch{}}
function unpin(id){storage.tabs=storage.tabs.filter(t=>t.id!==String(id))}
function go(t){try{const id=String(t.id),gid=t.guildId||channel(id)?.guild_id||channel(id)?.guildId;if(typeof ChannelRouter?.transitionToChannel==="function"){ChannelRouter.transitionToChannel(id);diag.navigation=true;return}if(typeof Nav?.transitionToGuild==="function"&&gid){Nav.transitionToGuild(String(gid),id);diag.navigation=true;return}if(typeof Nav?.transitionTo==="function"){Nav.transitionTo(`/channels/${gid||"@me"}/${id}`);diag.navigation=true;return}throw new Error("Navigation API bulunamadı")}catch(e){err("navigate",e);try{ui?.showToast?.("Kanal açılamadı") }catch{}}}
function haptic(){if(!storage.haptic)return;try{RN.Vibration?.vibrate?.(20)}catch{}}
function TabsBar(){if(!storage.enabled||!storage.tabs.length)return null;diag.renders++;const V=RN.View,T=RN.Text,P=RN.Pressable||RN.TouchableOpacity||V,SV=RN.ScrollView||V;if(!V||!T)return null;const active=currentId();const s={wrap:{backgroundColor:"#1e1f22",paddingVertical:storage.compact?4:6,borderTopWidth:0.5,borderTopColor:"#3f4147"},content:{paddingHorizontal:6,gap:5,alignItems:"center"},tab:{flexDirection:"row",alignItems:"center",paddingVertical:storage.compact?5:7,paddingHorizontal:storage.compact?7:9,borderRadius:8,backgroundColor:"#2b2d31",maxWidth:190},on:{backgroundColor:"#404eed"},tx:{color:"#f2f3f5",fontSize:storage.compact?12:13,maxWidth:140},x:{color:"#b5bac1",fontSize:15,paddingLeft:6}};return React.createElement(V,{style:s.wrap},React.createElement(SV,{horizontal:true,showsHorizontalScrollIndicator:false,contentContainerStyle:s.content},...storage.tabs.map(t=>React.createElement(P,{key:t.id,onPress:()=>{haptic();go(t)},style:[s.tab,t.id===active&&s.on]},React.createElement(T,{style:s.tx},storage.showNames?`# ${t.name||nameOf(channel(t.id))}`:"●"),storage.showClose?React.createElement(P,{onPress:e=>{try{e?.stopPropagation?.()}catch{};unpin(t.id);haptic()},hitSlop:8},React.createElement(T,{style:s.x},"×")):null))))}
function installBar(){try{const jsx=M.findByProps?.("jsx","jsxs");if(!jsx)return;for(const n of ["jsx","jsxs"]){if(typeof jsx[n]!=="function")continue;unpatches.push(patcher.before(n,jsx,args=>{try{if(guard||!storage.enabled||storage.position!=="aboveComposer")return;const type=args?.[0];const name=String(type?.displayName||type?.name||"");if(!/(ChatInput|ChannelTextArea|ChatInputRoot|ChatInputContainer)/i.test(name))return;const Original=type;const props=args[1];function Wrapped(p){guard=true;try{const original=React.createElement(Original,p);return React.createElement(React.Fragment,null,React.createElement(TabsBar),original)}finally{guard=false}}Wrapped.displayName="KettuChannelTabsWrapper";args[0]=Wrapped;args[1]=props;diag.jsx=true}catch(e){err("jsx",e)}}))}}catch(e){err("installBar",e)}}
function findRows(root){const seen=new WeakSet();let b=1000;function w(v,d){if(v==null||d>10||b--<0)return null;if(Array.isArray(v)&&v.some(x=>x?.props&&typeof x.props.onPress==="function"))return v;if(typeof v!=="object")return null;if(seen.has(v))return null;seen.add(v);for(const k of Object.keys(v)){if(typeof v[k]==="function")continue;const r=w(v[k],d+1);if(r)return r}return null}return w(root,0)}
function installSheet(){try{LazyActionSheet=M.findByProps?.("openLazy","hideActionSheet");ActionSheetRow=M.findByProps?.("ActionSheetRow")?.ActionSheetRow||common?.ActionSheetRow||ui?.components?.FormRow;if(!LazyActionSheet||!ActionSheetRow)return;unpatches.push(patcher.before("openLazy",LazyActionSheet,([component,key,props])=>{const c=props?.channel||props?.channelRecord;if(!c?.id||!component?.then)return;component.then(mod=>{if(typeof mod?.default!=="function")return;const u=patcher.after("default",mod,(_,tree)=>{setTimeout(()=>{try{u()}catch{}},0);const rows=findRows(tree);if(!rows||rows.some(x=>x?.props?.__kct))return;const is=storage.tabs.some(t=>t.id===String(c.id));rows.push(React.createElement(ActionSheetRow,{key:"kct",__kct:true,label:is?"Sekmeden çıkar":"Sekmeye sabitle",onPress:()=>{LazyActionSheet.hideActionSheet?.();is?unpin(c.id):pin(c)}}))});}).catch?.(()=>{})}));diag.sheet=true}catch(e){err("sheet",e)}}
function discover(){ChannelStore=M.findByStoreName?.("ChannelStore");SelectedChannelStore=M.findByStoreName?.("SelectedChannelStore")||M.findByProps?.("getChannelId","getVoiceChannelId");ChannelRouter=M.findByProps?.("transitionToChannel","transitionToThread");Nav=M.findByProps?.("transitionTo","transitionToGuild")}
function Settings(){if(!React||!RN.View||!RN.Text)return null;const[,f]=React.useReducer(x=>x+1,0),S=(k,v)=>{storage[k]=v;f()};const V=RN.View,T=RN.Text,SV=RN.ScrollView||V,Sw=RN.Switch,I=RN.TextInput,P=RN.Pressable||RN.TouchableOpacity||V;const st={root:{padding:16,gap:10},h:{fontSize:22,fontWeight:"700",color:"#fff"},c:{padding:12,borderRadius:10,backgroundColor:"#2b2d31",gap:8},t:{fontSize:15,color:"#fff",flex:1},s:{fontSize:12,color:"#b5bac1"},r:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},i:{backgroundColor:"#1e1f22",color:"#fff",padding:9,borderRadius:7},b:{padding:10,borderRadius:7,backgroundColor:"#404249"},bt:{color:"#fff",textAlign:"center",fontWeight:"600"}};const row=(l,k)=>React.createElement(V,{style:st.r},React.createElement(T,{style:st.t},l),Sw&&React.createElement(Sw,{value:!!storage[k],onValueChange:v=>S(k,v)}));const btn=(l,fn)=>React.createElement(P,{onPress:fn,style:st.b},React.createElement(T,{style:st.bt},l));const c=channel(currentId());return React.createElement(SV,{contentContainerStyle:st.root},React.createElement(T,{style:st.h},"ChannelTabs"),React.createElement(V,{style:st.c},row("Aktif","enabled"),row("Kanal isimlerini göster","showNames"),row("Sekmede × göster","showClose"),row("Kompakt görünüm","compact"),row("Dokununca hafif titreşim","haptic"),React.createElement(T,{style:st.s},"Maks sekme"),I&&React.createElement(I,{style:st.i,value:String(storage.maxTabs),keyboardType:"numeric",onChangeText:v=>S("maxTabs",v)})),React.createElement(V,{style:st.c},btn(c?`Şu anki kanalı sabitle: ${nameOf(c)}`:"Şu anki kanal bulunamadı",()=>{if(c){pin(c);f()}}),btn("Tüm sekmeleri temizle",()=>{storage.tabs=[];f()})),React.createElement(V,{style:st.c},React.createElement(T,{style:st.t},"Sabit sekmeler"),...(storage.tabs.length?storage.tabs.map(t=>React.createElement(V,{key:t.id,style:st.r},React.createElement(T,{style:st.s},`${t.name} • ${t.id}`),React.createElement(P,{onPress:()=>{unpin(t.id);f()}},React.createElement(T,{style:{color:"#f23f42"}},"Kaldır")))):[React.createElement(T,{key:"none",style:st.s},"Henüz sekme yok.")])),React.createElement(V,{style:st.c},React.createElement(T,{style:st.s},`ChatInput hook ${diag.jsx?"OK":"YOK"} | Kanal menüsü ${diag.sheet?"OK":"YOK"} | Navigation ${diag.navigation?"OK":"bekliyor"}\nRender ${diag.renders} | Pin ${diag.pins}${diag.lastError?`\n${diag.lastError}`:""}`)))}
function onLoad(){defaults();discover();installBar();installSheet()}function onUnload(){while(unpatches.length){try{unpatches.pop()?.()}catch{}}}
return {onLoad,onUnload,settings:Settings,__test:{pin,unpin,go,nameOf,currentId}};
})(vendetta.metro,vendetta.metro.common,vendetta.patcher,vendetta.plugin,vendetta.logger,vendetta.ui,vendetta.utils)
